import { createSlice } from "@reduxjs/toolkit";

/**
 * Initial state of the project slice.
 * @type {Object}
 * @property {string} projectName - The name of the project.
 */
const initialState = {
    projectName: ""
};

/**
 * Slice for managing project-related state.
 * @type {Object}
 * @property {string} name - The name of the slice.
 * @property {Object} initialState - The initial state of the slice.
 * @property {Object} reducers - The reducers for handling actions.
 */
export const ProjectSlice = createSlice({
    name: 'Project', // Name of the slice
    initialState, // Initial state of the slice
    reducers: {
        /**
         * Sets the project name in the state.
         * @param {Object} state - The current state.
         * @param {Object} action - The action object containing the payload.
         * @param {string} action.payload - The new project name to set.
         */
        setProjectName: (state, action) => {
            state.projectName = action.payload;
        },
    },
});

// Export the action creators generated by createSlice
export const { setUser } = ProjectSlice.actions;

/**
 * The reducer function for the ProjectSlice.
 * @type {function} - The reducer function to be used in the store.
 */
export default ProjectSlice.reducer;
